/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentReceivedRouteImport } from './routes/payment-received'
import { Route as IndexRouteImport } from './routes/index'

const PaymentReceivedRoute = PaymentReceivedRouteImport.update({
  id: '/payment-received',
  path: '/payment-received',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment-received': typeof PaymentReceivedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment-received': typeof PaymentReceivedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/payment-received': typeof PaymentReceivedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/payment-received'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/payment-received'
  id: '__root__' | '/' | '/payment-received'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaymentReceivedRoute: typeof PaymentReceivedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment-received': {
      id: '/payment-received'
      path: '/payment-received'
      fullPath: '/payment-received'
      preLoaderRoute: typeof PaymentReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaymentReceivedRoute: PaymentReceivedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
